services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db-api
      SPRING_DATASOURCE_USERNAME: huyleang
      SPRING_DATASOURCE_PASSWORD: 1di2y3r7y92o
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db-api
      POSTGRES_USER: huyleang
      POSTGRES_PASSWORD: 1di2y3r7y92o
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: